"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:58:26.976847+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, broadcast, when
from pyspark.sql.types import FloatType, StringType, DateType
import json
import os

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw CSV files with all columns as strings
    transactions_df = (spark.read.option("header", "true")
                      .option("inferSchema", "false")
                       .csv(input_path + "/transactions.csv"))

    merchants_df = (spark.read.option("header", "true")
                     .option("inferSchema", "false")
                     .csv(input_path + "/merchants.csv"))

    # Add metadata columns
    transactions_df = (transactions_df.withColumn("ingestion_timestamp", lit(run_date))
                      .withColumn("source_file", lit("transactions.csv"))
                       .withColumn("pipeline_run_id", lit(run_id)))

    # Write as Parquet partitioned by date
    transactions_df.write.mode("overwrite").partitionBy("ingestion_timestamp").parquet(output_path + "/bronze/transactions")
    merchants_df.write.mode("overwrite").partitionBy("ingestion_timestamp").parquet(output_path + "/bronze/merchants")

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    transactions_df = (spark.read.parquet(bronze_path + "/bronze/transactions")
                      .where(col("ingestion_timestamp") == run_date))

    merchants_df = (spark.read.parquet(merchants_path + "/bronze/merchants")
                   .where(col("ingestion_timestamp") == run_date)
                   .cache())  # Cache the small merchants table

    # Cast columns to correct types
    transactions_df = (transactions_df.withColumn("amount", col("amount").cast(FloatType()))
                        .withColumn("transaction_date", col("transaction_date").cast(DateType()))
                       .withColumn("transaction_id", col("transaction_id").cast(StringType()))
                       .withColumn("merchant_id", col("merchant_id").cast(StringType())))

    # Filter: remove records where transaction_id is NULL or amount < 0
    transactions_df = transactions_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))

    # Deduplicate: if same transaction_id appears twice, keep the record with latest ingestion_timestamp
    transactions_dedup_df = (transactions_df.groupBy("transaction_id")
                             .agg({"amount": "max", "ingestion_timestamp": "max"})
                            .withColumnsRenamed({"max(amount)": "amount", "max(ingestion_timestamp)": "ingestion_timestamp"}))

    # Enrich: join transactions with merchants on merchant_id to get merchant_name, category, city
    transactions_enriched_df = (transactions_dedup_df.join(broadcast(merchants_df), "merchant_id", "left_outer")
                               .withColumn("quality_flag", when(col("merchant_id").isNull(), "UNMATCHED").otherwise("CLEAN")))

    # Write as Parquet partitioned by date
    transactions_enriched_df.write.mode("overwrite").partitionBy("transaction_date").parquet(output_path + "/silver/transactions")

def main(spark, input_path, output_path, run_date, run_id):
    # Ingest Bronze layer
    ingest_bronze(spark, input_path, output_path, run_date, run_id)

    # Transform Silver layer
    transform_silver(spark, output_path, output_path, output_path, run_date)

    # Write run metadata summary to a JSON file
    metadata = {"run_date": run_date, "run_id": run_id, "status": "COMPLETE"}
    with open(os.path.join(output_path, "run_metadata.json"), "w") as f:
        json.dump(metadata, f)

if __name__ == "__main__":
    # Initialize Spark session
    spark = (SparkSession.builder
            .appName("Sigma DataTech Transaction Analytics Pipeline")
             .getOrCreate())

    # Define input and output paths
    input_path = "s3://your-bucket/bronze"
    output_path = "s3://your-bucket/silver"

    # Define run date and run ID
    run_date = "2026-05-27"
    run_id = "run_id_12345"

    # Execute the pipeline
    main(spark, input_path, output_path, run_date, run_id)


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, broadcast, when, avg, collect_set, coalesce, lit
from pyspark.sql.types import StructType, StructField, StringType, FloatType, DateType
import json

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Initialize run metadata
    run_metadata = {
        "run_date": run_date,
        "silver_path": silver_path,
        "gold_output_dir": gold_output_dir,
        "tables": []
    }
    
    # Build Gold tables
    build_merchant_performance(spark, silver_path, f"{gold_output_dir}/merchant_performance", run_date)
    build_customer_ltv(spark, silver_path, f"{gold_output_dir}/customer_ltv")
    build_daily_summary(spark, silver_path, f"{gold_output_dir}/daily_summary", run_date)
    
    # Write run metadata to JSON
    with open(f"{gold_output_dir}/run_metadata.json", "w") as f:
        json.dump(run_metadata, f)

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).where(col("date") == run_date)
    
    # Filter for completed transactions
    completed_txns = silver_df.where(col("status") == "COMPLETED")
    
    # Calculate metrics
    merchant_performance_df = completed_txns.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
       .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("txn_count")
        )
    
    # Calculate failure rate
    all_txns = silver_df.groupBy("merchant_id").agg(
        count("*").alias("total_txns"),
        count(when(col("status") == "FAILED", 1)).alias("failed_txns")
    )
    
    failure_rate_df = all_txns.withColumn("failure_rate_pct", (col("failed_txns") / col("total_txns") * 100).cast("float"))
    
    # Join metrics and failure rate
    final_df = merchant_performance_df.join(failure_rate_df, on=["merchant_id"], how="left") \
        .select("merchant_id", "merchant_name", "category", "city", "date", "total_revenue", "txn_count", "failure_rate_pct")
    
    # Write output
    final_df.write.mode("overwrite").partitionBy("date").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path)
    
    # Filter for completed transactions
    completed_txns = silver_df.where(col("status") == "COMPLETED")
    
    # Calculate metrics
    customer_ltv_df = completed_txns.groupBy("customer_id") \
       .agg(
            sum("amount").alias("total_spent"),
            count("*").alias("total_txns"),
            avg("amount").alias("avg_txn_value"),
            min("transaction_date").alias("first_txn_date"),
            max("transaction_date").alias("last_txn_date")
        )
    
    # Determine preferred payment method (mode)
    payment_method_df = completed_txns.groupBy("customer_id", "payment_method") \
       .agg(count("*").alias("payment_count")) \
       .groupBy("customer_id") \
       .agg(max("payment_count").alias("max_count"), collect_set("payment_method").alias("payment_methods")) \
        .withColumn("preferred_payment_method", coalesce(max("payment_methods")[0], lit(None)))
    
    # Join metrics and preferred payment method
    final_df = customer_ltv_df.join(payment_method_df, on=["customer_id"], how="left") \
       .select("customer_id", "total_spent", "total_txns", "avg_txn_value", "first_txn_date", "last_txn_date", "preferred_payment_method")
    
    # Write output
    final_df.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).where(col("date") == run_date)
    
    # Calculate metrics
    daily_summary_df = silver_df.groupBy("date") \
       .agg(
            sum(when(col("status") == "COMPLETED", col("amount")).otherwise(lit(0))).alias("total_revenue"),
            count("*").alias("total_txns"),
            count(col("customer_id").distinct()).alias("unique_customers"),
            count(col("merchant_id").distinct()).alias("unique_merchants")
        )
    
    # Calculate failure rate
    all_txns = silver_df.groupBy("date").agg(
        count("*").alias("total_txns"),
        count(when(col("status") == "FAILED", 1)).alias("failed_txns")
    )
    
    failure_rate_df = all_txns.withColumn("failure_rate_pct", (col("failed_txns") / col("total_txns") * 100).cast("float"))
    
    # Join metrics and failure rate
    final_df = daily_summary_df.join(failure_rate_df, on=["date"], how="left") \
       .select("date", "total_revenue", "total_txns", "unique_customers", "unique_merchants", "failure_rate_pct")
    
    # Write output
    final_df.write.mode("overwrite").partitionBy("date").parquet(output_path)
